- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: Printing Variables
    ansible.builtin.debug:
     msg: "We are learning {{NAME}}, Duration is: {{DURATION}}, Trainer is : {{TRAINER}}"