- name: variables at task level
  hosts: localhost
  vars:
  - money: "10000 Rs"
    land: "120 hectares"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add & Override
    vars:
    - money: "20000 Rs"
      houses: "3 houses"
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}" 