- name: testing variable precedence
  hosts: mongodb
  #vars:
  # NAME: naga-play
  #vars_files:
  #- variables.yaml
  #vars_prompt:
  #- name: NAME
  # prompt: Please enter Trainee Name
  # private: false
  tasks:
  - name: variable at task level
   # vars:
   #   NAME: naga-task
    ansible.builtin.debug:
      msg: "Trainer Name is : {{NAME}}" 