- name: create user
  host: localhost
  tasks:
  - name: check roboshop user exits or not
    ansible.builtin.command: id roboshop
    register: output
  - name: print the command output
    ansible.builtin.debug:
     msg: "output is : {{output}}"